spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

  datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:

  h2:
    console:
      enabled: true
      settings:
          trace: false
          web-allow-others: false

